//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 02:09:10 PM EST 
//


package com.programming4phone.accidents.charlotte.wsdl;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ACCIDENTS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCIDENTS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EVENT_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DATETIME_ADD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="DIVISION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EVENT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EVENT_DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="X_COORD" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Y_COORD" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="LATITUDE" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="LONGITUDE" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCIDENTS", propOrder = {
    "eventno",
    "datetimeadd",
    "division",
    "address",
    "eventtype",
    "eventdesc",
    "xcoord",
    "ycoord",
    "latitude",
    "longitude"
})
public class ACCIDENTS {

    @XmlElement(name = "EVENT_NO")
    protected String eventno;
    @XmlElement(name = "DATETIME_ADD", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetimeadd;
    @XmlElement(name = "DIVISION")
    protected String division;
    @XmlElement(name = "ADDRESS")
    protected String address;
    @XmlElement(name = "EVENT_TYPE")
    protected String eventtype;
    @XmlElement(name = "EVENT_DESC")
    protected String eventdesc;
    @XmlElement(name = "X_COORD", required = true)
    protected BigDecimal xcoord;
    @XmlElement(name = "Y_COORD", required = true)
    protected BigDecimal ycoord;
    @XmlElement(name = "LATITUDE", required = true)
    protected BigDecimal latitude;
    @XmlElement(name = "LONGITUDE", required = true)
    protected BigDecimal longitude;

    /**
     * Gets the value of the eventno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTNO() {
        return eventno;
    }

    /**
     * Sets the value of the eventno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTNO(String value) {
        this.eventno = value;
    }

    /**
     * Gets the value of the datetimeadd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATETIMEADD() {
        return datetimeadd;
    }

    /**
     * Sets the value of the datetimeadd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATETIMEADD(XMLGregorianCalendar value) {
        this.datetimeadd = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIVISION() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIVISION(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the eventtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTTYPE() {
        return eventtype;
    }

    /**
     * Sets the value of the eventtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTTYPE(String value) {
        this.eventtype = value;
    }

    /**
     * Gets the value of the eventdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTDESC() {
        return eventdesc;
    }

    /**
     * Sets the value of the eventdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTDESC(String value) {
        this.eventdesc = value;
    }

    /**
     * Gets the value of the xcoord property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getXCOORD() {
        return xcoord;
    }

    /**
     * Sets the value of the xcoord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXCOORD(BigDecimal value) {
        this.xcoord = value;
    }

    /**
     * Gets the value of the ycoord property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYCOORD() {
        return ycoord;
    }

    /**
     * Sets the value of the ycoord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYCOORD(BigDecimal value) {
        this.ycoord = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLATITUDE() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLATITUDE(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLONGITUDE() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLONGITUDE(BigDecimal value) {
        this.longitude = value;
    }

}
