//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 02:09:10 PM EST 
//


package com.programming4phone.accidents.charlotte.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CMPDAccidentsResult" type="{http://maps.cmpd.org/}ArrayOfACCIDENTS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmpdAccidentsResult"
})
@XmlRootElement(name = "CMPDAccidentsResponse")
public class CMPDAccidentsResponse {

    @XmlElement(name = "CMPDAccidentsResult")
    protected ArrayOfACCIDENTS cmpdAccidentsResult;

    /**
     * Gets the value of the cmpdAccidentsResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfACCIDENTS }
     *     
     */
    public ArrayOfACCIDENTS getCMPDAccidentsResult() {
        return cmpdAccidentsResult;
    }

    /**
     * Sets the value of the cmpdAccidentsResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfACCIDENTS }
     *     
     */
    public void setCMPDAccidentsResult(ArrayOfACCIDENTS value) {
        this.cmpdAccidentsResult = value;
    }

}
