//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.19 at 02:09:10 PM EST 
//


package com.programming4phone.accidents.charlotte.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.programming4phone.accidents.charlotte.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.programming4phone.accidents.charlotte.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CMPDAccidents }
     * 
     */
    public CMPDAccidents createCMPDAccidents() {
        return new CMPDAccidents();
    }

    /**
     * Create an instance of {@link CMPDAccidentsResponse }
     * 
     */
    public CMPDAccidentsResponse createCMPDAccidentsResponse() {
        return new CMPDAccidentsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfACCIDENTS }
     * 
     */
    public ArrayOfACCIDENTS createArrayOfACCIDENTS() {
        return new ArrayOfACCIDENTS();
    }

    /**
     * Create an instance of {@link ACCIDENTS }
     * 
     */
    public ACCIDENTS createACCIDENTS() {
        return new ACCIDENTS();
    }

}
